# Generated by Django 3.2.6 on 2021-08-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='taken_books',
            field=models.ManyToManyField(to='book.Book'),
        ),
    ]
